zoneway:
  profile: target/uploadPath

spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://192.168.30.53:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ry
        password: Ry@202411
  redis:
    host: 192.168.30.53
    database: 5
    password: Zoneway@202405

wx:
  miniapp:
    configs:
      - appid: wxb7f60d404ab6529f
        secret: 5e3028562835af4301abbd45d0bf0ea8
        token: 2GVvnybOlO5dYZsO
        aesKey: B73HYnupuyOeqiOvQBBnJ3gPQjbYC1E83uSRx9Ys3dz
        msgDataFormat: JSON
  mp:
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111
#多实例配置
wechat:
  cp:
    appConfigs:
      - agentId: 1000001
        corpId: xxxx
        secret: 1111
        token: 111
        aesKey: 111
      - agentId: 1000002
        corpId: xxxx
        secret: 1111
        token: 111
        aesKey: 111
